cmake_minimum_required(VERSION 3.8)
project(single_lwr_robot)
find_package(ament_cmake REQUIRED)
install(DIRECTORY robot DESTINATION share/${PROJECT_NAME})
install(DIRECTORY config DESTINATION share/${PROJECT_NAME})
install(DIRECTORY worlds DESTINATION share/${PROJECT_NAME})
install(DIRECTORY launch DESTINATION share/${PROJECT_NAME})
if(BUILD_TESTING)
  find_package(ament_cmake_pytest REQUIRED)
  ament_add_pytest_test(model test/test_model.py TIMEOUT 60)
endif()
ament_package()
