cmake_minimum_required(VERSION 3.8)
project(cartesian_position_node)
find_package(ament_cmake REQUIRED)
foreach(dependency rclcpp sensor_msgs std_msgs geometry_msgs lwr_controllers kdl_parser orocos_kdl_vendor)
  find_package(${dependency} REQUIRED)
endforeach()
add_executable(cartesian_position_node src/cartesian_position_node.cpp)
target_compile_features(cartesian_position_node PUBLIC cxx_std_17)
target_compile_options(cartesian_position_node PRIVATE -Wall -Wextra -Wpedantic)
ament_target_dependencies(cartesian_position_node
  rclcpp sensor_msgs std_msgs geometry_msgs lwr_controllers kdl_parser orocos_kdl_vendor)
install(TARGETS cartesian_position_node DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY launch DESTINATION share/${PROJECT_NAME})
if(BUILD_TESTING)
  find_package(ament_cmake_pytest REQUIRED)
  ament_add_pytest_test(test_cartesian_position test/test_cartesian_position.py TIMEOUT 90
    APPEND_ENV ROS_LOG_DIR=${CMAKE_CURRENT_BINARY_DIR}/ros_test_logs)
endif()
ament_package()
